boot.o: boot.S multiboot.h x86_desc.h types.h
irq.o: irq.S x86_desc.h types.h
system_call_wrapper.o: system_call_wrapper.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exception.o: exception.c exception.h lib.h types.h
file_system.o: file_system.c file_system.h types.h lib.h system_call.h \
  paging.h kb.h x86_desc.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c x86_desc.h types.h idt.h exception.h lib.h kb.h irq.h rtc.h \
  i8259.h system_call_wrapper.h
kb.o: kb.c kb.h types.h i8259.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h kb.h irq.h exception.h paging.h file_system.h \
  system_call.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h
rtc.o: rtc.c rtc.h lib.h types.h kb.h i8259.h irq.h
system_call.o: system_call.c system_call.h file_system.h types.h lib.h \
  paging.h kb.h x86_desc.h rtc.h i8259.h irq.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h rtc.h kb.h i8259.h \
  irq.h file_system.h system_call.h paging.h
